# Generated by Django 3.1.5 on 2021-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('body', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'titles',
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва2')),
                ('body', models.TextField(verbose_name='text')),
                ('image', models.ImageField(upload_to='reg/image', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'title2',
                'verbose_name_plural': 'titles2',
            },
        ),
    ]
